# Generated by Django 6.0.4 on 2026-04-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_office',
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_type',
            field=models.CharField(choices=[('OFFICE', 'Στο Γραφείο'), ('REMOTE', 'Μέσω Διαδικτύου')], default='REMOTE', max_length=10, verbose_name='Τρόπος Εργασίας'),
        ),
    ]
