# Generated by Django 6.0.4 on 2026-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Παρουσία', 'verbose_name_plural': 'Παρουσίες'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_type',
            field=models.CharField(choices=[('OFFICE', 'Στο Γραφείο'), ('REMOTE', 'Τηλεργασία'), ('LEAVE', 'Άδεια'), ('SICK', 'Ασθένεια')], max_length=10, verbose_name='Τύπος Εργασίας'),
        ),
    ]
