# Generated by Django 6.0.4 on 2026-05-05 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_attendance_options_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Εγγραφής'),
            preserve_default=False,
        ),
    ]
