# Generated by Django 6.0.4 on 2026-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_attendance_is_office_attendance_work_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work_type',
            field=models.CharField(choices=[('OFFICE', 'Στο Γραφείο'), ('REMOTE', 'Τηλεργασία')], default='REMOTE', max_length=10, verbose_name='Τρόπος Εργασίας'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
