# Generated by Django 6.0.4 on 2026-05-05 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.date.today, verbose_name='Ημερομηνία εγγραφής'),
        ),
    ]
