# Generated by Django 6.0.4 on 2026-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='initial_debt',
            field=models.IntegerField(default=0, verbose_name='Αρχικό Χρέος Ημερών'),
        ),
    ]
